[package]
name = "bitcrypto"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
rust-crypto = "0.2.36"
siphasher = {version="0.1.1",registry="susytech"}
primitives = { path = "../primitives" }
